version: '3'

services:

  db:
    image: postgres:10
    ports:
      - '5321:5432'
    environment:
      - POSTGRES_USER=disa
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=disa_db
    volumes:
      - ./disa_pgdata:/var/lib/postgresql/data
    container_name: disa_db
    networks:
      - disa_app

  back:
    build: './backend'
    ports:
      - '8000:8000'
    container_name: disa_back
    depends_on: 
      - 'db'
    networks:
      - disa_app

  front: 
    build: './frontend'
    network_mode: 'host'
    container_name: disa_front
    depends_on:
      - 'back'
      - 'db'

networks:
  disa_app:
    driver: bridge





